### ISSUE TITLE
Initial Website Design

### ISSUE THREAD

**Issue by Mustafif** [E-M-Innovations/FASTAPI-Quiz#7]

**Comment by TeomanEgeSelcuk** [comment]
**_To-do List:_**

**Neeraj:**

- [ ] Create the main page structure for the website 
- [ ] Select a theme for the main page 
- [ ] Create clickable text boxes for each theme of quizzes
- [ ] Implement a visual feedback when a textbox is clicked (e.g., change color or add an outline)
- [ ] Develop the functionality to load all available quiz names when a quiz theme is clicked on 


**Ege:**

- [ ] Create textboxes for all test names 
- [ ] Implement the functionality to change the color of the clicked test names to appear darker
- [ ] Allow the user to undo their selection by clicking the test once again
- [ ] Add a "Done" button that will be clickable after all tests are selected
     - [ ]  Style the "Done" button to appear darker in color when clicked
 - [ ] Develop the functionality to load all randomized questions after the user clicks on the "Done" button

**Mustafif:**

- [ ] Implement a single question per page feature 
- [ ] Create selection options for all choices of the question
    - [ ] Develop the functionality to undo a previous selection if the user clicks on another selection
- [ ] Create a submit box for users to submit their answers after selecting a choice
   - [ ] Disable the ability to go back to previous questions after submitting them
   - [ ] Add a simple animation to indicate whether the submitted answer is correct or incorrect
- [ ] After all the questions are submitted the user can press submit all for the Grading Process

**Comment by Mustafif** [comment]
I created a branch to push changes to, make sure to pull changes from `master` then you may use `git switch 7-initial-web-design` to access the branch from remote locally.
